// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2AD4DbLCz6iqpHBVEs_G6Ov5QU-eOCC0',
    appId: '1:409169085905:web:d21ef6b64f73c22eff8cf0',
    messagingSenderId: '409169085905',
    projectId: 'campuspulse-4254f',
    authDomain: 'campuspulse-4254f.firebaseapp.com',
    databaseURL: 'https://campuspulse-4254f-default-rtdb.firebaseio.com',
    storageBucket: 'campuspulse-4254f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmdqzpcp0rpY8MvVzQLBfQVZkygY01Poo',
    appId: '1:409169085905:android:07e93ccbf1179276ff8cf0',
    messagingSenderId: '409169085905',
    projectId: 'campuspulse-4254f',
    databaseURL: 'https://campuspulse-4254f-default-rtdb.firebaseio.com',
    storageBucket: 'campuspulse-4254f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp7x06NMdd8qzuqBDwREEpQQoB7118YUs',
    appId: '1:409169085905:ios:0d165a4d6fafd000ff8cf0',
    messagingSenderId: '409169085905',
    projectId: 'campuspulse-4254f',
    databaseURL: 'https://campuspulse-4254f-default-rtdb.firebaseio.com',
    storageBucket: 'campuspulse-4254f.firebasestorage.app',
    iosBundleId: 'com.example.campuspulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp7x06NMdd8qzuqBDwREEpQQoB7118YUs',
    appId: '1:409169085905:ios:0d165a4d6fafd000ff8cf0',
    messagingSenderId: '409169085905',
    projectId: 'campuspulse-4254f',
    databaseURL: 'https://campuspulse-4254f-default-rtdb.firebaseio.com',
    storageBucket: 'campuspulse-4254f.firebasestorage.app',
    iosBundleId: 'com.example.campuspulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2AD4DbLCz6iqpHBVEs_G6Ov5QU-eOCC0',
    appId: '1:409169085905:web:29d897d5defff5baff8cf0',
    messagingSenderId: '409169085905',
    projectId: 'campuspulse-4254f',
    authDomain: 'campuspulse-4254f.firebaseapp.com',
    databaseURL: 'https://campuspulse-4254f-default-rtdb.firebaseio.com',
    storageBucket: 'campuspulse-4254f.firebasestorage.app',
  );
}
